routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BureauController;
use App\Http\Controllers\EmployeController;
use App\Http\Controllers\DirectionController;
use App\Http\Controllers\InterphoneController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('Bureau',BureauController::class);
Route::resource('Direction',DirectionController::class);
Route::resource('Employe',EmployeController::class);
Route::resource('Interphone',InterphoneController::class);

app/Models/Bureau.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bureau extends Model
{
    use HasFactory;

    protected $table = "bureaux";

    protected $fillable = [
        'nom_bureau', 'emplacement'
    ];



    // relations 

    public function interphones(){
        return $this->hasMany(Interphone::class);
    }
    
    public function Employe(){
        return $this->hasMany(Employe::class);
    }




}

app/Http/Controllers/BureauController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bureau;
use Illuminate\Http\Request;

class BureauController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $Bureaux =  Bureau::all();
        return view('Bureau.index', compact('Bureaux'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Bureau.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'nom_bureau'=>'required',
            'emplacement'=>'required'
        ]);

    $bureau= new Bureau([
        'nom_bureau'=> $request->get('nom_bureau'),
        'emplacement'=>$request->get('emplacement')
    ]);

    $bureau->save();
    return redirect()->route('Bureau.index')->with('success', 'Bureau ajouté avec succès ');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Bureau  $bureau
     * @return \Illuminate\Http\Response
     */
    public function show(Bureau $Bureau)
    {
        //
        $Bureau = Bureau::findOrFail($Bureau->id);
        return view('Bureau.show', compact('Bureau'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Bureau  $bureau
     * @return \Illuminate\Http\Response
     */
   public function edit(Bureau $Bureau)
    {
        //
        $Bureau = Bureau::findOrFail($Bureau->id);
        return view('Bureau.edit', compact('Bureau'));
  

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Bureau  $bureau
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bureau $Bureau)
    {
        //
        $request->validate([
            'nom_bureau'=>'required',
            'emplacement'=>'required'
        ]);

        $Bureau = Bureau::findOrFail($Bureau->id);
        $Bureau->nom_bureau = $request->get('nom_bureau');
        $Bureau->emplacement = $request->get('emplacement');

        $Bureau->update();
        return redirect()->route('Bureau.index')->with('success', 'Bureau modifié avec succès');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Bureau  $bureau
     * @return \Illuminate\Http\Response
     */
    //public function destroy(Bureau $Bureau)
    public function destroy($Bureau)
    {
        //
        $bureau = Bureau::findOrFail($Bureau);
        
        $bureau->delete();
      return redirect()->route('Bureau.index')->with('success','Bureau supprimé avec succès');
    }
}

resources/views/Bureau/create.blade.php
@extends('layouts.app')

@section('content')

    <h1>Ajouter un bureau</h1>


    @if ($errors->any())

        <div class="alert alert-danger">

            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach

            </ul>

        </div>

    @endif
    <form action="{{route('Bureau.store')}}" method="post">
        @csrf

        <div class="form-group mb-3">
            <label for="nom_bureau">Nom</label>
            <input type="text" class="form-control" id="nom_bureau" placeholder="Entrez le bureau" name="nom_bureau">
        </div>

        <div class="form-group mb-3">

            <label for="emplacement">Emplacement</label>
            <input type="text" class="form-control" id="emplacement" placeholder="Entrez l'emplacement du bureau" name="emplacement">

        </div>
        

    
        <button type="submit" class="btn btn-primary">Enregister</button>

    </form>
@endsection

resources/views/Bureau/edit.blade.php
@section('content')

@extends('layouts.app')

    <h1>Modifier bureaux</h1>


   @if ($errors->any())

        <div class="alert alert-danger">

          <ul>
               @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>

        </div>

  @endif

    <form action="{{route('Bureau.update', $Bureau)}}" method="post"  >

        @method('PATCH')
        @csrf


        <div class="form-group mb-3">

            <label for="nom_bureau">Nom:</label>
            <input type="text" class="form-control" id="nom_bureau" name="nom_bureau" value="{{ $Bureau->nom_bureau }}">

        </div>

        <div class="form-group mb-3">

            <label for="emplacement">Emplacement:</label>
            <input type="text" class="form-control" id="emplacement" name="emplacement" value="{{ $Bureau->emplacement }}">

        </div>


        <button type="submit" class="btn btn-primary">Enregistrer</button>

    </form>

@endsection

resources/views/Bureau/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">

        <div class="col-lg-11">

            <h2>Gestion des bureaux</h2>

        </div>

        <div class="col-lg-1">
            <a class="btn btn-success" href="{{ url('Bureau/create') }}">Ajouter</a>
        </div>

    </div>

    @if ($message = Session::get('success'))

        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>

    @endif



    <table class="table table-bordered">

        <tr>

            <th>No</th>
            <th>Nom </th>
            <th>Emplacement</th>
            <th>Actions</th>

        </tr>

        @foreach ($Bureaux as $index => $Bureau)

            <tr>
                <td>{{ $Bureau->id}}</td>
                <td>{{ $Bureau->nom_bureau }}</td>
                <td>{{ $Bureau->emplacement }}</td>
                <td>

                        <a class="btn btn-info" href="{{ route('Bureau.show', $Bureau) }}">Voir</a>
                        <a class="btn btn-primary" href="{{ route('Bureau.edit', $Bureau) }}">Modifier</a>
                    <form action="{{ route('Bureau.destroy', $Bureau) }}" method="POST">
                        @csrf
                        @method('DELETE')
                       <!-- <a class="btn btn-danger" onclick="return confirm('Voulez-vous vraiment supprimmer ?')">Supprimer</a> -->
                        <button class="btn btn-danger" onclick="return confirm('Voulez-vous vraiment supprimmer ?')" type="submit">Supprimer</button>
                    

                    </form>
                </td>

            </tr>

        @endforeach
    </table>

@endsection

resources/views/Bureau/show.blade.php
@extends('layouts.app')


@section('content')

    <h1>Gestion des bureaux</h1>


    <table class="table table-bordered">

        <tr>
            <th>Nom:</th>
            <td>{{ $Bureau->nom_bureau }}</td>
        </tr>

        <tr>

            <th>Emplacement:</th>
            <td>{{ $Bureau->emplacement }}</td>

        </tr>

        
    </table>

@endsection