routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BureauController;
use App\Http\Controllers\EmployeController;
use App\Http\Controllers\DirectionController;
use App\Http\Controllers\InterphoneController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('Bureau',BureauController::class);
Route::resource('Direction',DirectionController::class);
Route::resource('Employe',EmployeController::class);
Route::resource('Interphone',InterphoneController::class);

app/Models/Direction.php
<?php

namespace App\Models;

use App\Models\Direction;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Direction extends Model
{
    use HasFactory;
    protected $fillable = [
        'nom_direction', 'sigle'
    ];

    public function Employe(){
        return $this->hasMany(Employe::class);
    }

}

app/Http/Controllers/DirectionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Direction;
use Illuminate\Http\Request;

class DirectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $Directions =  Direction::all();
        return view('Direction.index', compact('Directions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Direction.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'nom_direction'=>'required',
            'sigle'=>'required'
        ]);

    $direction= new Direction([
        'nom_direction'=> $request->get('nom_direction'),
        'sigle'=>$request->get('sigle')
    ]);

    $direction->save();
    return redirect()->route('Direction.index')->with('success', 'Direction ajoutée avec succès ');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Direction  $direction
     * @return \Illuminate\Http\Response
     */
    public function show(Direction $Direction)
    {
        //
        $Direction = Direction::findOrFail($Direction->id);
        return view('Direction.show', compact('Direction'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Direction  $direction
     * @return \Illuminate\Http\Response
     */
   public function edit(Direction $Direction)
    {
        //
        $Direction = Direction::findOrFail($Direction->id);
        return view('Direction.edit', compact('Direction'));
  

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Direction  $direction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Direction $Direction)
    {
        //
        $request->validate([
            'nom_direction'=>'required',
            'sigle'=>'required'
        ]);

        $Direction = Direction::findOrFail($Direction->id);
        $Direction->nom_direction= $request->get('nom_direction');
        $Direction->sigle = $request->get('sigle');

        $Direction->update();
        return redirect()->route('Direction.index')->with('success', 'Direction modifiée avec succès');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Direction  $direction
     * @return \Illuminate\Http\Response
     */

    public function destroy($Direction)
    {
        //
        $direction = Direction::findOrFail($Direction);
        
        $direction->delete();
      return redirect()->route('Direction.index')->with('success','Direction supprimée avec succès');
    }
}
    

resources/views/Direction/create.blade.php
@extends('layouts.app')

@section('content')

    <h1>Ajouter une nouvelle direction</h1>


    @if ($errors->any())

        <div class="alert alert-danger">

            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach

            </ul>

        </div>

    @endif
    <form action="{{route('Direction.store')}}" method="post">
        @csrf

        <div class="form-group mb-3">
            <label for="nom_direction">Nom:</label>
            <input type="text" class="form-control" id="nom_direction" placeholder="Entrez un nom" name="nom_direction">
        </div>

        <div class="form-group mb-3">

            <label for="sigle">Sigle:</label>
            <input type="text" class="form-control" id="sigle" placeholder="sigle" name="sigle">

        </div>


        <button type="submit" class="btn btn-primary">Enregister</button>

    </form>
@endsection

resources/views/Direction/edit.blade.php
@section('content')

@extends('layouts.app')

    <h1>Modifier directions</h1>


   @if ($errors->any())

        <div class="alert alert-danger">

          <ul>
               @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>

        </div>

  @endif

    <form action="{{route('Direction.update', $Direction)}}" method="post"  >

        @method('PATCH')
        @csrf


        <div class="form-group mb-3">

            <label for="nom_direction">Nom:</label>
            <input type="text" class="form-control" id="nom_direction" name="nom_direction" value="{{ $Direction->nom_direction }}">

        </div>

        <div class="form-group mb-3">

            <label for="sigle">Sigle:</label>
            <input type="text" class="form-control" id="sigle" name="sigle" value="{{ $Direction->sigle }}">

        </div>


        <button type="submit" class="btn btn-primary">Enregistrer</button>

    </form>

@endsection

resources/views/Direction/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">

        <div class="col-lg-11">

            <h2>Gestion des bureaux</h2>

        </div>

        <div class="col-lg-1">
            <a class="btn btn-success" href="{{ url('Direction/create') }}">Ajouter</a>
        </div>

    </div>

    @if ($message = Session::get('success'))

        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>

    @endif



    <table class="table table-bordered">

        <tr>

            <th>No</th>
            <th>Nom </th>
            <th>Sigle</th>
            <th>Actions</th>

        </tr>

        @foreach ($Directions as $index => $Direction)

            <tr>
                <td>{{ $Direction->id }}</td>
                <td>{{ $Direction->nom_direction }}</td>
                <td>{{ $Direction->sigle }}</td>
                <td>

                    
                        <a class="btn btn-info" href="{{ route('Direction.show', $Direction) }}">Voir</a>
                        <a class="btn btn-primary" href="{{ route('Direction.edit', $Direction) }}">Modifier</a>
                        <form action="{{ route('Direction.destroy', $Direction) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" onclick="return confirm('Voulez-vous vraiment supprimmer ?')" type="submit">Supprimer</button>
                    
                    </form>
                </td>

            </tr>

        @endforeach
    </table>

@endsection

resources/views/Direction/show.blade.php
@extends('layouts.app')


@section('content')

    <h1>Gestion des bureaux</h1>


    <table class="table table-bordered">

        <tr>
            <th>Nom:</th>
            <td>{{ $Direction->nom_direction }}</td>
        </tr>

        <tr>

            <th>Sigle:</th>
            <td>{{ $Direction->sigle }}</td>

        </tr>

        
    </table>

@endsection