routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BureauController;
use App\Http\Controllers\EmployeController;
use App\Http\Controllers\DirectionController;
use App\Http\Controllers\InterphoneController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('Bureau',BureauController::class);
Route::resource('Direction',DirectionController::class);
Route::resource('Employe',EmployeController::class);
Route::resource('Interphone',InterphoneController::class);

app/Models/Employe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employe extends Model
{
    use HasFactory;

    //relations


    protected $fillable = [
        'nom_employe', 'prenom_employe','groupe_employe','statut_employe','directions_id','bureaux_id'
    ];

    public function bureau(){
        return $this->belongsTo(Bureau::class, "bureaux_id");
    }

    public function direction(){
        return $this->belongsTo(Direction::class, "directions_id");
    }
}

app/Http/Controllers/EmployeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employe;
use App\Models\Direction;
use App\Models\Bureau;
use Illuminate\Http\Request;

class EmployeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
       // $Employes =  Employe::all();
        $Employes =  Employe::with('direction')->get();
        $Employes =  Employe::with('bureau')->get();
        return view('Employe.index', compact('Employes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $directions = Direction::all();
        $bureaux = Bureau::all();
        return view('Employe.create', compact('directions','bureaux'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
       // dd($request->all());
        $request->validate([
            'nom_employe'=>'required',
            'prenom_employe'=>'required',
            'groupe_employe'=>'required',
            'statut_employe'=>'required',
            'directions_id' => 'required',
            'bureaux_id' => 'required'
        ]);

    $employe= new Employe([
        'nom_employe'=> $request->get('nom_employe'),
        'prenom_employe'=>$request->get('prenom_employe'),
        'groupe_employe'=>$request->get('groupe_employe'),
        'statut_employe'=>$request->get('statut_employe'),
        'directions_id'=> $request->get('directions_id'),
        'bureaux_id'=> $request->get('bureaux_id'),
    ]);

    $employe->save();
    return redirect()->route('Employe.index')->with('success', 'Employé ajouté avec succès ');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employe  $employe
     * @return \Illuminate\Http\Response
     */
    public function show(Employe $Employe)
    {
        //
        $Employe = Employe::with('direction','bureau')->findOrfail($Employe->id);
        return view('Employe.show', compact('Employe'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employe  $employe
     * @return \Illuminate\Http\Response
     */
   public function edit(Employe $Employe)
    {
        //
         $Employe = Employe::findOrFail($Employe->id);
          $directions = Direction::all();
          $bureaux = Bureau::all();
        return view('Employe.edit', compact('Employe','bureaux','directions'));
  

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employe  $employe
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employe $Employe)
    {
        //
        $request->validate([
            'nom_employe'=>'required',
            'prenom_employe'=>'required',
            'groupe_employe'=>'required',
            'statut_employe'=>'required',
            'directions_id'=>'required',
            'bureaux_id'=>'required'
        ]);

        $Employe = Employe::findOrFail($Employe->id);
        $Employe->nom_employe = $request->get('nom_employe');
        $Employe->prenom_employe = $request->get('prenom_employe');
        $Employe->groupe_employe = $request->get('groupe_employe');
        $Employe->statut_employe = $request->get('statut_employe');
        $Employe->directions_id = $request->get('directions_id');
        $Employe->bureaux_id = $request->get('bureaux_id');

        $Employe->update();
        return redirect()->route('Employe.index')->with('success', 'Employé modifié avec succès');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employe  $employe
     * @return \Illuminate\Http\Response
     */
    public function destroy($Employe)
    {
        //
        $employe = Employe::findOrFail($Employe);
        
        $employe->delete();
      return redirect()->route('Employe.index')->with('success','Employé supprimé avec succès');
    }
}

resources/views/Employe/create.blade.php
@extends('layouts.app')

@section('content')

    <h1>Ajouter un employé</h1>


    @if ($errors->any())

        <div class="alert alert-danger">

            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach

            </ul>

        </div>

    @endif
    <form action="{{route('Employe.store')}}" method="post">
        @csrf

        <div class="form-group mb-3">
            <label for="nom_employe">Nom:</label>
            <input type="text" class="form-control" id="nom_employe" placeholder="Entrez le nom de l'employé " name="nom_employe">
        </div>

        <div class="form-group mb-3">

            <label for="prenom_employe">Prenom:</label>
            <input type="text" class="form-control" id="prenom_employe" placeholder="Entrez le prenom de l'employé" name="prenom_employe">

        </div>

        <div class="form-group mb-3">

            <label for="groupe_employe">Groupé:</label>
            <input type="text" class="form-control" id="groupe_employe" placeholder="Entrez le numéro groupé de l'employé" name="groupe_employe">

        </div>

        <div class="form-group mb-3">

            <label for="statut_employe">Statut:</label>
            <input type="text" class="form-control" id="statut_employe" placeholder="Entrez le statut de l'employé" name="statut_employe">

        </div>
        
        <div class="form-group mb-3">
        <label for="directions_id" class="label">Direction:</label>
            <select name="directions_id" id="directions_id" class="select form-control">
                <option value=""></option>
                @foreach($directions as $direction)
                    <option value="{{$direction->id}}">{{$direction->nom_direction}}</option>
                @endforeach
            </select>


            <label for="bureaux_id" class="label">Bureau:</label>
            <select name="bureaux_id" id="bureaux_id" class="select form-control">
                <option value=""></option>
                @foreach($bureaux as $bureau)
                    <option value="{{$bureau->id}}">{{$bureau->nom_bureau}}</option>
                @endforeach
            </select>
</div>


       
        <button type="submit" class="btn btn-primary">Enregister</button>

    </form>
@endsection

resources/views/Employe/edit.blade.php
@section('content')

@extends('layouts.app')

    <h1>Modifier employés</h1>


   @if ($errors->any())

        <div class="alert alert-danger">

          <ul>
               @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>

        </div>

  @endif

    <form action="{{route('Employe.update', $Employe)}}" method="post"  >

        @method('PATCH')
        @csrf


        <div class="form-group mb-3">

            <label for="nom_direction">Nom:</label>
            <input type="text" class="form-control" id="nom_employe" name="nom_employe" value="{{ $Employe->nom_employe }}">

        </div>

        <div class="form-group mb-3">

            <label for="sigle">Prenom:</label>
            <input type="text" class="form-control" id="prenom_employe" name="prenom_employe" value="{{ $Employe->prenom_employe}}">

        </div>

        <div class="form-group mb-3">

            <label for="sigle">Groupé:</label>
            <input type="text" class="form-control" id="groupe_employe" placeholder="Groupé" name="groupe_employe" value="{{ $Employe->groupe_employe}}">

        </div>

        <div class="form-group mb-3">

            <label for="sigle">Statut:</label>
            <input type="text" class="form-control" id="statut_employe" placeholder="Statut" name="statut_employe" value="{{ $Employe->statut_employe}}">
            <label for="directions_id" class="label">Direction</label>
            <select name="directions_id" id="directions_id" class="select form-control">
                <option value=""></option>
                @foreach($directions as $direction)
                    <option value="{{$direction->id}}" {{ ($Employe->directions_id == $direction->id) ? "selected=selected" : '' }} > {{$direction->nom_direction}}</option>
                @endforeach
            </select>
        

            <label for="bureaux_id" class="label">Bureau</label>
            <select name="bureaux_id" id="bureaux_id" class="select form-control">
                <option value=""></option>
                @foreach($bureaux as $bureau)
                    <option value="{{$bureau->id}}" {{ ($Employe->bureaux_id == $bureau->id) ? "selected=selected" : '' }} > {{$bureau->nom_bureau}}</option>
                @endforeach
            </select>
</div>
        <button type="submit" class="btn btn-primary">Enregistrer</button>

</form>

@endsection

resources/views/Employe/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">

        <div class="col-lg-11">

            <h2>Gestion des bureaux</h2>

        </div>

        <div class="col-lg-1">
            <a class="btn btn-success" href="{{ url('Employe/create') }}">Ajouter</a>
        </div>

    </div>

    @if ($message = Session::get('success'))

        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>

    @endif



    <table class="table table-bordered">

        <tr>

            <th>No</th>
            <th>Nom </th>
            <th>Prénom</th>
            <th>Groupé</th>
            <th>Statut</th>
            <th>Direction</th>
            <th>Bureau</th>
            <th>Actions</th>

        </tr>

        @foreach ($Employes as $index => $Employe)

            <tr>
                <td>{{ $index +1 }}</td>
                <td>{{ $Employe->nom_employe }}</td>
                <td>{{ $Employe->prenom_employe }}</td>
                <td>{{ $Employe->groupe_employe }}</td>
                <td>{{ $Employe->statut_employe }}</td>
                <td>{{ $Employe->direction->nom_direction }}</td>
                <td>{{ $Employe->bureau->nom_bureau }}</td>
                <td>

                    
                        <a class="btn btn-info" href="{{ route('Employe.show', $Employe) }}">Voir</a>
                        <a class="btn btn-primary" href="{{ route('Employe.edit', $Employe) }}">Modifier</a>
                        <form action="{{ route('Employe.destroy', $Employe) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" onclick="return confirm('Voulez-vous vraiment supprimmer ?')" type="submit">Supprimer</button>
                    
                    </form>
                </td>

            </tr>

        @endforeach
    </table>

@endsection

resources/views/Employe/show.blade.php
@extends('layouts.app')


@section('content')

    <h1>Gestion des bureaux</h1>


    <table class="table table-bordered">

        <tr>
            <th>Nom:</th>
            <td>{{ $Employe->nom_employe }}</td>
        </tr>

        <tr>

            <th>Prenom:</th>
            <td>{{ $Employe->prenom_employe }}</td>

        </tr>

        <tr>

            <th>Groupé:</th>
            <td>{{ $Employe->groupe_employe }}</td>

        </tr>

        <tr>

            <th>Statut:</th>
            <td>{{ $Employe->statut_employe }}</td>

        </tr>

        <tr>

            <th>Direction:</th>
            <td>{{ $Employe->direction->nom_direction }}</td>

        </tr>

        <tr>

            <th>Bureau:</th>
            <td>{{ $Employe->bureau->nom_bureau }}</td>

        </tr>

        
    </table>

@endsection