routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BureauController;
use App\Http\Controllers\EmployeController;
use App\Http\Controllers\DirectionController;
use App\Http\Controllers\InterphoneController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('Bureau',BureauController::class);
Route::resource('Direction',DirectionController::class);
Route::resource('Employe',EmployeController::class);
Route::resource('Interphone',InterphoneController::class);

app/Models/Interphone.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Interphone extends Model
{
    use HasFactory;




    // relations

    protected $fillable = [
        'numero_interphone','bureaux_id'
    ];

    public function bureau(){
        return $this->belongsTo(Bureau::class, "bureaux_id");
    }
}

app/Http/Controllers/InterphoneController.php
<?php

namespace App\Http\Controllers;

use App\Models\Interphone;
use App\Models\Bureau;
use Illuminate\Http\Request;

class InterphoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $Interphones =  Interphone::with('bureau')->get();
        //dd($Interphones);
        return view('Interphone.index', compact('Interphones'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $bureaux = Bureau::all(); 
        return view('Interphone.create', compact('bureaux'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        //dd($request->get('numero_interphone'));
        $request->validate([
            'numero_interphone'=>'required',
            'bureaux_id' => 'required'
        ]);

    $interphone= new Interphone([
        'numero_interphone'=> $request->get('numero_interphone'),
        'bureaux_id'=> $request->get('bureaux_id'),
    ]);

    $interphone->save();
    return redirect()->route('Interphone.index')->with('success', 'Interphone ajouté avec succès ');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Interphone  $interphone
     * @return \Illuminate\Http\Response
     */
    public function show(Interphone $Interphone)
    {
        //
        $Interphone = Interphone::with('bureau')->findOrFail($Interphone->id);
        return view('Interphone.show', compact('Interphone'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Interphone  $interphone
     * @return \Illuminate\Http\Response
     */
   public function edit(Interphone $Interphone)
    {
        //
        $Interphone = Interphone::with('bureau')->findOrFail($Interphone->id);
        $bureaux = Bureau::all(); 
        return view('Interphone.edit', compact('Interphone','bureaux'));
  

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Interphone  $interphone
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Interphone $Interphone)
    {
        //
        $request->validate([
            'numero_interphone'=>'required',
            'bureaux_id'=>'required',
            
        ]);

        $Interphone = Interphone::findOrFail($Interphone->id);
        $Interphone->numero_interphone= $request->get('numero_interphone');
        $Interphone->bureaux_id= $request->get('bureaux_id');

        $Interphone->update();
        return redirect()->route('Interphone.index')->with('success', 'Interphone modifié avec succès');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Interphone  $interphone
     * @return \Illuminate\Http\Response
     */

    public function destroy($Interphone)
    {
        //
        $interphone = Interphone::findOrFail($Interphone);
        
        $interphone->delete();
      return redirect()->route('Interphone.index')->with('success','Interphone supprimé avec succès');
    }
}
    

resources/views/Interphone/create.blade.php
@extends('layouts.app')

@section('content')

    <h1>Ajouter un interphone</h1>


    @if ($errors->any())

        <div class="alert alert-danger">

            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach

            </ul>

        </div>

    @endif
    <form action="{{route('Interphone.store')}}" method="post">
        @csrf

        <div class="form-group mb-3">
            <label for="numero_interphone">Numéro Interphone</label>
            <input type="text" class="form-control" id="numero_interphone" placeholder="Entrez un numéro" name="numero_interphone">
            <label for="bureaux_id" class="label">Bureau</label>
            <select name="bureaux_id" id="bureaux_id" class="select form-control">
                <option value=""></option>
                @foreach($bureaux as $bureau)
                    <option value="{{$bureau->id}}">{{$bureau->nom_bureau}}</option>
                @endforeach
            </select>
        </div>

      
        <button type="submit" class="btn btn-primary">Enregister</button>

    </form>
@endsection

resources/views/Interphone/edit.blade.php
@section('content')

@extends('layouts.app')

    <h1>Modifier Interphone</h1>


   @if ($errors->any())

        <div class="alert alert-danger">

          <ul>
               @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>

        </div>

  @endif

    <form action="{{route('Interphone.update', $Interphone)}}" method="post"  >

        @method('PATCH')
        @csrf


        <div class="form-group mb-3">

            <label for="numero_interphone">Numéro Interphone</label>
            <input type="text" class="form-control" id="numero_interphone" name="numero_interphone" value="{{ $Interphone->numero_interphone }}">
            <label for="bureaux_id" class="label">Bureau</label>
            <select name="bureaux_id" id="bureaux_id" class="select form-control">
                <option value=""></option>
                @foreach($bureaux as $bureau)
                    <option value="{{$bureau->id}}" {{ ($Interphone->bureaux_id == $bureau->id) ? "selected=selected" : '' }} > {{$bureau->nom_bureau}}</option>
                @endforeach
            </select>
            </div>

        <button type="submit" class="btn btn-primary">Enregistrer</button>

    </form>

@endsection

resources/views/Interphone/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">

        <div class="col-lg-11">

            <h2>Gestion des bureaux</h2>

        </div>

        <div class="col-lg-1">
            <a class="btn btn-success" href="{{ url('Interphone/create') }}">Ajouter</a>
        </div>

    </div>

    @if ($message = Session::get('success'))

        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>

    @endif



    <table class="table table-bordered">

        <tr>

            <th>No</th>
            <th>Numéro Interphone </th>
            <th>Bureau</th>
            <th>Actions</th>

        </tr>

        @foreach ($Interphones as $index => $Interphone)

            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $Interphone->numero_interphone }}</td>
                <td>{{ $Interphone->bureau->nom_bureau}}</td>
                <td>

                    
                        <a class="btn btn-info" href="{{ route('Interphone.show', $Interphone) }}">Voir</a>
                        <a class="btn btn-primary" href="{{ route('Interphone.edit', $Interphone) }}">Modifier</a>
                        <form action="{{ route('Interphone.destroy', $Interphone) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" onclick="return confirm('Voulez-vous vraiment supprimmer ?')" type="submit">Supprimer</button>
                    
                    </form>
                </td>

            </tr>

        @endforeach
    </table>

@endsection

resources/views/Interphone/show.blade.php
@extends('layouts.app')


@section('content')

    <h1>Gestion des bureaux</h1>


    <table class="table table-bordered">

        <tr>
            <th>Numéro Interphone:</th>
            <td>{{ $Interphone->numero_interphone }}</td>
        </tr>
        <tr>    
            <th>Bureau:</th>
            <td>{{ $Interphone->bureau->nom_bureau }}</td>

        </tr>
        
    </table>

@endsection